### ISSUE TITLE
Testing frontend

### ISSUE THREAD

**Issue by MaLiN2223** [tea-lang-org/tea-lang#31]
I was trying to run `test_frontend.py` but I noticed that it is depended on some datasets that are not uploaded with the code. 
Do you mind uploading them or removing the test?
I am working on making Travis to use all test files so the repository wouldn't have regressions like in #30 or #29 but `test_frontend.py` breaks. It seems like a good test except it's lacking data. 

cc @emjun

**Comment by emjun** [comment]
I re-organized the tests: 
- Removed `test_frontend.py` because it was from an early experiment designing Tea. It was fun to look at again and inspired some new ideas/thoughts, but it doesn't need to be in the tests for Tea right now. 😄 (see [commit](https://github.com/emjun/tea-lang/tree/f35536d601fa5a552f70c119b0bb5ece3ba3c7a9))
- Moved `tests/integration_tests/tea_eval.py` into a `evals/tea_eval.py` because `tea_eval.py` isn't really a test of Tea. It's an evaluation comparing Tea to other Python stats libraries. That and other evaluations in the future should go in `evals/`. (see [commit](https://github.com/emjun/tea-lang/tree/a93dc6ad249d9519c6b99b8af034b3e319e216a2))

**Comment by emjun** [comment]
Happy to keep discussing, but I'm going to close this issue for now!
